[electrodes]
# List of all channel (electrode) names expected in the input files
head_file = ['I', 'II', 'III', 'AVR', 'AVL', 'AVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'HISp', 'HISd', 'VD p', 'VD 78', 'VD 56', 'VD 34', 'VD d']
# Subset of channels to be processed
head = ['VD d', 'I', 'II', 'III', 'AVR', 'AVL', 'AVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']

[data]
# Input directory or file
input = ./input/
# Input File (1) or Input Directory (0)
input_file = 0
# Output directory
output_dir = ./output/
# Raw Data (1) or Processed Data (0)
raw_data = 1
; # Input directory or file
; input = ./output/ecg_data.txt
; # Input File (1) or Input Directory (0)
; input_file = 1
; # Output directory
; output_dir = ./output/
; # Raw Data (1) or Processed Data (0)
; raw_data = 0

[marking]
# Clean signal (1) or not (0)
clean_signal = 0
# Read simulated ECG from MonoAlg3D (1) or real ECG from the electrophysiological study (0)
ecg_mono = 0
# Vertical offset between electrode signals in the visualization window
offset = 1000
# Uncertainty in marking (ms)
uncertainty = 15 